package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbAlmoxarifado generated by hbm2java
 */
public class TbAlmoxarifado  implements java.io.Serializable {


     private int almoId;
     private TbAlmoxarifadoHasEstoque tbAlmoxarifadoHasEstoque;
     private Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino = new HashSet(0);
     private Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem = new HashSet(0);
     private Set tbEstoques = new HashSet(0);
     private Set tbEntradas = new HashSet(0);
     private Set tbFuncionarios = new HashSet(0);
     private Set tbFuncionarios_1 = new HashSet(0);

    public TbAlmoxarifado() {
    }

	
    public TbAlmoxarifado(int almoId) {
        this.almoId = almoId;
    }
    public TbAlmoxarifado(int almoId, TbAlmoxarifadoHasEstoque tbAlmoxarifadoHasEstoque, Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino, Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem, Set tbEstoques, Set tbEntradas, Set tbFuncionarios, Set tbFuncionarios_1) {
       this.almoId = almoId;
       this.tbAlmoxarifadoHasEstoque = tbAlmoxarifadoHasEstoque;
       this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino = tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino;
       this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem = tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem;
       this.tbEstoques = tbEstoques;
       this.tbEntradas = tbEntradas;
       this.tbFuncionarios = tbFuncionarios;
       this.tbFuncionarios_1 = tbFuncionarios_1;
    }
   
    public int getAlmoId() {
        return this.almoId;
    }
    
    public void setAlmoId(int almoId) {
        this.almoId = almoId;
    }
    public TbAlmoxarifadoHasEstoque getTbAlmoxarifadoHasEstoque() {
        return this.tbAlmoxarifadoHasEstoque;
    }
    
    public void setTbAlmoxarifadoHasEstoque(TbAlmoxarifadoHasEstoque tbAlmoxarifadoHasEstoque) {
        this.tbAlmoxarifadoHasEstoque = tbAlmoxarifadoHasEstoque;
    }
    public Set getTbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino() {
        return this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino;
    }
    
    public void setTbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino(Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino) {
        this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino = tbTransferenciasAlmoxarifadosForTraAlmoxarifadoDestino;
    }
    public Set getTbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem() {
        return this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem;
    }
    
    public void setTbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem(Set tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem) {
        this.tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem = tbTransferenciasAlmoxarifadosForTraAlmoxarifadoOrigem;
    }
    public Set getTbEstoques() {
        return this.tbEstoques;
    }
    
    public void setTbEstoques(Set tbEstoques) {
        this.tbEstoques = tbEstoques;
    }
    public Set getTbEntradas() {
        return this.tbEntradas;
    }
    
    public void setTbEntradas(Set tbEntradas) {
        this.tbEntradas = tbEntradas;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbFuncionarios_1() {
        return this.tbFuncionarios_1;
    }
    
    public void setTbFuncionarios_1(Set tbFuncionarios_1) {
        this.tbFuncionarios_1 = tbFuncionarios_1;
    }




}


