package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbAlmoxarifadoHasEstoque generated by hbm2java
 */
public class TbAlmoxarifadoHasEstoque  implements java.io.Serializable {


     private int almoId;
     private TbAlmoxarifado tbAlmoxarifado;
     private int estoId;
     private String tbAlmoxarifadoHasEstoquecol;

    public TbAlmoxarifadoHasEstoque() {
    }

	
    public TbAlmoxarifadoHasEstoque(TbAlmoxarifado tbAlmoxarifado, int estoId) {
        this.tbAlmoxarifado = tbAlmoxarifado;
        this.estoId = estoId;
    }
    public TbAlmoxarifadoHasEstoque(TbAlmoxarifado tbAlmoxarifado, int estoId, String tbAlmoxarifadoHasEstoquecol) {
       this.tbAlmoxarifado = tbAlmoxarifado;
       this.estoId = estoId;
       this.tbAlmoxarifadoHasEstoquecol = tbAlmoxarifadoHasEstoquecol;
    }
   
    public int getAlmoId() {
        return this.almoId;
    }
    
    public void setAlmoId(int almoId) {
        this.almoId = almoId;
    }
    public TbAlmoxarifado getTbAlmoxarifado() {
        return this.tbAlmoxarifado;
    }
    
    public void setTbAlmoxarifado(TbAlmoxarifado tbAlmoxarifado) {
        this.tbAlmoxarifado = tbAlmoxarifado;
    }
    public int getEstoId() {
        return this.estoId;
    }
    
    public void setEstoId(int estoId) {
        this.estoId = estoId;
    }
    public String getTbAlmoxarifadoHasEstoquecol() {
        return this.tbAlmoxarifadoHasEstoquecol;
    }
    
    public void setTbAlmoxarifadoHasEstoquecol(String tbAlmoxarifadoHasEstoquecol) {
        this.tbAlmoxarifadoHasEstoquecol = tbAlmoxarifadoHasEstoquecol;
    }




}


