package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbCidEstId generated by hbm2java
 */
public class TbCidEstId  implements java.io.Serializable {


     private int ceCidId;
     private String ceEstSigla;

    public TbCidEstId() {
    }

    public TbCidEstId(int ceCidId, String ceEstSigla) {
       this.ceCidId = ceCidId;
       this.ceEstSigla = ceEstSigla;
    }
   
    public int getCeCidId() {
        return this.ceCidId;
    }
    
    public void setCeCidId(int ceCidId) {
        this.ceCidId = ceCidId;
    }
    public String getCeEstSigla() {
        return this.ceEstSigla;
    }
    
    public void setCeEstSigla(String ceEstSigla) {
        this.ceEstSigla = ceEstSigla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbCidEstId) ) return false;
		 TbCidEstId castOther = ( TbCidEstId ) other; 
         
		 return (this.getCeCidId()==castOther.getCeCidId())
 && ( (this.getCeEstSigla()==castOther.getCeEstSigla()) || ( this.getCeEstSigla()!=null && castOther.getCeEstSigla()!=null && this.getCeEstSigla().equals(castOther.getCeEstSigla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCeCidId();
         result = 37 * result + ( getCeEstSigla() == null ? 0 : this.getCeEstSigla().hashCode() );
         return result;
   }   


}


