package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbCidade generated by hbm2java
 */
public class TbCidade  implements java.io.Serializable {


     private Integer cidId;
     private String cidDescricao;
     private Set tbCidEsts = new HashSet(0);

    public TbCidade() {
    }

	
    public TbCidade(String cidDescricao) {
        this.cidDescricao = cidDescricao;
    }
    public TbCidade(String cidDescricao, Set tbCidEsts) {
       this.cidDescricao = cidDescricao;
       this.tbCidEsts = tbCidEsts;
    }
   
    public Integer getCidId() {
        return this.cidId;
    }
    
    public void setCidId(Integer cidId) {
        this.cidId = cidId;
    }
    public String getCidDescricao() {
        return this.cidDescricao;
    }
    
    public void setCidDescricao(String cidDescricao) {
        this.cidDescricao = cidDescricao;
    }
    public Set getTbCidEsts() {
        return this.tbCidEsts;
    }
    
    public void setTbCidEsts(Set tbCidEsts) {
        this.tbCidEsts = tbCidEsts;
    }




}


