package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbEntradaEstoque generated by hbm2java
 */
public class TbEntradaEstoque  implements java.io.Serializable {


     private int entreId;
     private TbFornecedor tbFornecedor;
     private TbEntrada tbEntrada;
     private TbProduto tbProduto;

    public TbEntradaEstoque() {
    }

    public TbEntradaEstoque(int entreId, TbFornecedor tbFornecedor, TbEntrada tbEntrada, TbProduto tbProduto) {
       this.entreId = entreId;
       this.tbFornecedor = tbFornecedor;
       this.tbEntrada = tbEntrada;
       this.tbProduto = tbProduto;
    }
   
    public int getEntreId() {
        return this.entreId;
    }
    
    public void setEntreId(int entreId) {
        this.entreId = entreId;
    }
    public TbFornecedor getTbFornecedor() {
        return this.tbFornecedor;
    }
    
    public void setTbFornecedor(TbFornecedor tbFornecedor) {
        this.tbFornecedor = tbFornecedor;
    }
    public TbEntrada getTbEntrada() {
        return this.tbEntrada;
    }
    
    public void setTbEntrada(TbEntrada tbEntrada) {
        this.tbEntrada = tbEntrada;
    }
    public TbProduto getTbProduto() {
        return this.tbProduto;
    }
    
    public void setTbProduto(TbProduto tbProduto) {
        this.tbProduto = tbProduto;
    }




}


