package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEntrada generated by hbm2java
 */
public class TbEntrada  implements java.io.Serializable {


     private int entrId;
     private TbTransferenciaStatus tbTransferenciaStatus;
     private TbAlmoxarifado tbAlmoxarifado;
     private Set tbEntradaEstoques = new HashSet(0);

    public TbEntrada() {
    }

	
    public TbEntrada(int entrId, TbTransferenciaStatus tbTransferenciaStatus, TbAlmoxarifado tbAlmoxarifado) {
        this.entrId = entrId;
        this.tbTransferenciaStatus = tbTransferenciaStatus;
        this.tbAlmoxarifado = tbAlmoxarifado;
    }
    public TbEntrada(int entrId, TbTransferenciaStatus tbTransferenciaStatus, TbAlmoxarifado tbAlmoxarifado, Set tbEntradaEstoques) {
       this.entrId = entrId;
       this.tbTransferenciaStatus = tbTransferenciaStatus;
       this.tbAlmoxarifado = tbAlmoxarifado;
       this.tbEntradaEstoques = tbEntradaEstoques;
    }
   
    public int getEntrId() {
        return this.entrId;
    }
    
    public void setEntrId(int entrId) {
        this.entrId = entrId;
    }
    public TbTransferenciaStatus getTbTransferenciaStatus() {
        return this.tbTransferenciaStatus;
    }
    
    public void setTbTransferenciaStatus(TbTransferenciaStatus tbTransferenciaStatus) {
        this.tbTransferenciaStatus = tbTransferenciaStatus;
    }
    public TbAlmoxarifado getTbAlmoxarifado() {
        return this.tbAlmoxarifado;
    }
    
    public void setTbAlmoxarifado(TbAlmoxarifado tbAlmoxarifado) {
        this.tbAlmoxarifado = tbAlmoxarifado;
    }
    public Set getTbEntradaEstoques() {
        return this.tbEntradaEstoques;
    }
    
    public void setTbEntradaEstoques(Set tbEntradaEstoques) {
        this.tbEntradaEstoques = tbEntradaEstoques;
    }




}


