package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEndPostal generated by hbm2java
 */
public class TbEndPostal  implements java.io.Serializable {


     private int endPId;
     private TbLogradouro tbLogradouro;
     private TbBairro tbBairro;
     private TbCidEst tbCidEst;
     private String endPNomeRua;
     private String endCep;
     private Set tbEnderecos = new HashSet(0);

    public TbEndPostal() {
    }

	
    public TbEndPostal(int endPId, TbLogradouro tbLogradouro, TbBairro tbBairro, TbCidEst tbCidEst, String endPNomeRua, String endCep) {
        this.endPId = endPId;
        this.tbLogradouro = tbLogradouro;
        this.tbBairro = tbBairro;
        this.tbCidEst = tbCidEst;
        this.endPNomeRua = endPNomeRua;
        this.endCep = endCep;
    }
    public TbEndPostal(int endPId, TbLogradouro tbLogradouro, TbBairro tbBairro, TbCidEst tbCidEst, String endPNomeRua, String endCep, Set tbEnderecos) {
       this.endPId = endPId;
       this.tbLogradouro = tbLogradouro;
       this.tbBairro = tbBairro;
       this.tbCidEst = tbCidEst;
       this.endPNomeRua = endPNomeRua;
       this.endCep = endCep;
       this.tbEnderecos = tbEnderecos;
    }
   
    public int getEndPId() {
        return this.endPId;
    }
    
    public void setEndPId(int endPId) {
        this.endPId = endPId;
    }
    public TbLogradouro getTbLogradouro() {
        return this.tbLogradouro;
    }
    
    public void setTbLogradouro(TbLogradouro tbLogradouro) {
        this.tbLogradouro = tbLogradouro;
    }
    public TbBairro getTbBairro() {
        return this.tbBairro;
    }
    
    public void setTbBairro(TbBairro tbBairro) {
        this.tbBairro = tbBairro;
    }
    public TbCidEst getTbCidEst() {
        return this.tbCidEst;
    }
    
    public void setTbCidEst(TbCidEst tbCidEst) {
        this.tbCidEst = tbCidEst;
    }
    public String getEndPNomeRua() {
        return this.endPNomeRua;
    }
    
    public void setEndPNomeRua(String endPNomeRua) {
        this.endPNomeRua = endPNomeRua;
    }
    public String getEndCep() {
        return this.endCep;
    }
    
    public void setEndCep(String endCep) {
        this.endCep = endCep;
    }
    public Set getTbEnderecos() {
        return this.tbEnderecos;
    }
    
    public void setTbEnderecos(Set tbEnderecos) {
        this.tbEnderecos = tbEnderecos;
    }




}


