package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbEntidade generated by hbm2java
 */
public class TbEntidade  implements java.io.Serializable {


     private String entCpfCnpj;
     private TbEndereco tbEndereco;
     private TbSexo tbSexo;
     private String entNome;
     private String entNomeFantasia;
     private String entRgIe;
     private String entFone;
     private String entEmail;
     private Date entDtNasc;
     private String entTipo;
     private Set tbFilials = new HashSet(0);
     private Set tbFornecedors = new HashSet(0);
     private Set tbFuncionarios = new HashSet(0);
     private Set tbClientes = new HashSet(0);
     private Set tbEnderecos = new HashSet(0);

    public TbEntidade() {
    }

	
    public TbEntidade(String entCpfCnpj, TbEndereco tbEndereco, String entNome, String entNomeFantasia, String entRgIe, String entFone, String entEmail, String entTipo) {
        this.entCpfCnpj = entCpfCnpj;
        this.tbEndereco = tbEndereco;
        this.entNome = entNome;
        this.entNomeFantasia = entNomeFantasia;
        this.entRgIe = entRgIe;
        this.entFone = entFone;
        this.entEmail = entEmail;
        this.entTipo = entTipo;
    }
    public TbEntidade(String entCpfCnpj, TbEndereco tbEndereco, TbSexo tbSexo, String entNome, String entNomeFantasia, String entRgIe, String entFone, String entEmail, Date entDtNasc, String entTipo, Set tbFilials, Set tbFornecedors, Set tbFuncionarios, Set tbClientes, Set tbEnderecos) {
       this.entCpfCnpj = entCpfCnpj;
       this.tbEndereco = tbEndereco;
       this.tbSexo = tbSexo;
       this.entNome = entNome;
       this.entNomeFantasia = entNomeFantasia;
       this.entRgIe = entRgIe;
       this.entFone = entFone;
       this.entEmail = entEmail;
       this.entDtNasc = entDtNasc;
       this.entTipo = entTipo;
       this.tbFilials = tbFilials;
       this.tbFornecedors = tbFornecedors;
       this.tbFuncionarios = tbFuncionarios;
       this.tbClientes = tbClientes;
       this.tbEnderecos = tbEnderecos;
    }
   
    public String getEntCpfCnpj() {
        return this.entCpfCnpj;
    }
    
    public void setEntCpfCnpj(String entCpfCnpj) {
        this.entCpfCnpj = entCpfCnpj;
    }
    public TbEndereco getTbEndereco() {
        return this.tbEndereco;
    }
    
    public void setTbEndereco(TbEndereco tbEndereco) {
        this.tbEndereco = tbEndereco;
    }
    public TbSexo getTbSexo() {
        return this.tbSexo;
    }
    
    public void setTbSexo(TbSexo tbSexo) {
        this.tbSexo = tbSexo;
    }
    public String getEntNome() {
        return this.entNome;
    }
    
    public void setEntNome(String entNome) {
        this.entNome = entNome;
    }
    public String getEntNomeFantasia() {
        return this.entNomeFantasia;
    }
    
    public void setEntNomeFantasia(String entNomeFantasia) {
        this.entNomeFantasia = entNomeFantasia;
    }
    public String getEntRgIe() {
        return this.entRgIe;
    }
    
    public void setEntRgIe(String entRgIe) {
        this.entRgIe = entRgIe;
    }
    public String getEntFone() {
        return this.entFone;
    }
    
    public void setEntFone(String entFone) {
        this.entFone = entFone;
    }
    public String getEntEmail() {
        return this.entEmail;
    }
    
    public void setEntEmail(String entEmail) {
        this.entEmail = entEmail;
    }
    public Date getEntDtNasc() {
        return this.entDtNasc;
    }
    
    public void setEntDtNasc(Date entDtNasc) {
        this.entDtNasc = entDtNasc;
    }
    public String getEntTipo() {
        return this.entTipo;
    }
    
    public void setEntTipo(String entTipo) {
        this.entTipo = entTipo;
    }
    public Set getTbFilials() {
        return this.tbFilials;
    }
    
    public void setTbFilials(Set tbFilials) {
        this.tbFilials = tbFilials;
    }
    public Set getTbFornecedors() {
        return this.tbFornecedors;
    }
    
    public void setTbFornecedors(Set tbFornecedors) {
        this.tbFornecedors = tbFornecedors;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(Set tbClientes) {
        this.tbClientes = tbClientes;
    }
    public Set getTbEnderecos() {
        return this.tbEnderecos;
    }
    
    public void setTbEnderecos(Set tbEnderecos) {
        this.tbEnderecos = tbEnderecos;
    }




}


