package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEndereco generated by hbm2java
 */
public class TbEndereco  implements java.io.Serializable {


     private Integer endId;
     private TbEndPostal tbEndPostal;
     private int endNumero;
     private String endComplemento;
     private Set tbEntidades = new HashSet(0);
     private Set tbEntidades_1 = new HashSet(0);

    public TbEndereco() {
    }

	
    public TbEndereco(TbEndPostal tbEndPostal, int endNumero) {
        this.tbEndPostal = tbEndPostal;
        this.endNumero = endNumero;
    }
    public TbEndereco(TbEndPostal tbEndPostal, int endNumero, String endComplemento, Set tbEntidades, Set tbEntidades_1) {
       this.tbEndPostal = tbEndPostal;
       this.endNumero = endNumero;
       this.endComplemento = endComplemento;
       this.tbEntidades = tbEntidades;
       this.tbEntidades_1 = tbEntidades_1;
    }
   
    public Integer getEndId() {
        return this.endId;
    }
    
    public void setEndId(Integer endId) {
        this.endId = endId;
    }
    public TbEndPostal getTbEndPostal() {
        return this.tbEndPostal;
    }
    
    public void setTbEndPostal(TbEndPostal tbEndPostal) {
        this.tbEndPostal = tbEndPostal;
    }
    public int getEndNumero() {
        return this.endNumero;
    }
    
    public void setEndNumero(int endNumero) {
        this.endNumero = endNumero;
    }
    public String getEndComplemento() {
        return this.endComplemento;
    }
    
    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }
    public Set getTbEntidades() {
        return this.tbEntidades;
    }
    
    public void setTbEntidades(Set tbEntidades) {
        this.tbEntidades = tbEntidades;
    }
    public Set getTbEntidades_1() {
        return this.tbEntidades_1;
    }
    
    public void setTbEntidades_1(Set tbEntidades_1) {
        this.tbEntidades_1 = tbEntidades_1;
    }




}


