package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbEstoqueId generated by hbm2java
 */
public class TbEstoqueId  implements java.io.Serializable {


     private int estoAlmoxarifado;
     private String estoProdutoCodigo;

    public TbEstoqueId() {
    }

    public TbEstoqueId(int estoAlmoxarifado, String estoProdutoCodigo) {
       this.estoAlmoxarifado = estoAlmoxarifado;
       this.estoProdutoCodigo = estoProdutoCodigo;
    }
   
    public int getEstoAlmoxarifado() {
        return this.estoAlmoxarifado;
    }
    
    public void setEstoAlmoxarifado(int estoAlmoxarifado) {
        this.estoAlmoxarifado = estoAlmoxarifado;
    }
    public String getEstoProdutoCodigo() {
        return this.estoProdutoCodigo;
    }
    
    public void setEstoProdutoCodigo(String estoProdutoCodigo) {
        this.estoProdutoCodigo = estoProdutoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbEstoqueId) ) return false;
		 TbEstoqueId castOther = ( TbEstoqueId ) other; 
         
		 return (this.getEstoAlmoxarifado()==castOther.getEstoAlmoxarifado())
 && ( (this.getEstoProdutoCodigo()==castOther.getEstoProdutoCodigo()) || ( this.getEstoProdutoCodigo()!=null && castOther.getEstoProdutoCodigo()!=null && this.getEstoProdutoCodigo().equals(castOther.getEstoProdutoCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEstoAlmoxarifado();
         result = 37 * result + ( getEstoProdutoCodigo() == null ? 0 : this.getEstoProdutoCodigo().hashCode() );
         return result;
   }   


}


