package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbFilial generated by hbm2java
 */
public class TbFilial  implements java.io.Serializable {


     private int filId;
     private TbEntidade tbEntidade;
     private String filPreferencias;
     private Set tbFuncionarios = new HashSet(0);
     private Set tbFuncionarios_1 = new HashSet(0);

    public TbFilial() {
    }

	
    public TbFilial(int filId, TbEntidade tbEntidade, String filPreferencias) {
        this.filId = filId;
        this.tbEntidade = tbEntidade;
        this.filPreferencias = filPreferencias;
    }
    public TbFilial(int filId, TbEntidade tbEntidade, String filPreferencias, Set tbFuncionarios, Set tbFuncionarios_1) {
       this.filId = filId;
       this.tbEntidade = tbEntidade;
       this.filPreferencias = filPreferencias;
       this.tbFuncionarios = tbFuncionarios;
       this.tbFuncionarios_1 = tbFuncionarios_1;
    }
   
    public int getFilId() {
        return this.filId;
    }
    
    public void setFilId(int filId) {
        this.filId = filId;
    }
    public TbEntidade getTbEntidade() {
        return this.tbEntidade;
    }
    
    public void setTbEntidade(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public String getFilPreferencias() {
        return this.filPreferencias;
    }
    
    public void setFilPreferencias(String filPreferencias) {
        this.filPreferencias = filPreferencias;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbFuncionarios_1() {
        return this.tbFuncionarios_1;
    }
    
    public void setTbFuncionarios_1(Set tbFuncionarios_1) {
        this.tbFuncionarios_1 = tbFuncionarios_1;
    }




}


