package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbFornecedorHasProdutoId generated by hbm2java
 */
public class TbFornecedorHasProdutoId  implements java.io.Serializable {


     private int fhpId;
     private String fhpPdt;

    public TbFornecedorHasProdutoId() {
    }

    public TbFornecedorHasProdutoId(int fhpId, String fhpPdt) {
       this.fhpId = fhpId;
       this.fhpPdt = fhpPdt;
    }
   
    public int getFhpId() {
        return this.fhpId;
    }
    
    public void setFhpId(int fhpId) {
        this.fhpId = fhpId;
    }
    public String getFhpPdt() {
        return this.fhpPdt;
    }
    
    public void setFhpPdt(String fhpPdt) {
        this.fhpPdt = fhpPdt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbFornecedorHasProdutoId) ) return false;
		 TbFornecedorHasProdutoId castOther = ( TbFornecedorHasProdutoId ) other; 
         
		 return (this.getFhpId()==castOther.getFhpId())
 && ( (this.getFhpPdt()==castOther.getFhpPdt()) || ( this.getFhpPdt()!=null && castOther.getFhpPdt()!=null && this.getFhpPdt().equals(castOther.getFhpPdt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFhpId();
         result = 37 * result + ( getFhpPdt() == null ? 0 : this.getFhpPdt().hashCode() );
         return result;
   }   


}


