package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbFornecedor generated by hbm2java
 */
public class TbFornecedor  implements java.io.Serializable {


     private Integer forId;
     private TbEntidade tbEntidade;
     private Set tbEntradaEstoques = new HashSet(0);
     private Set tbFornecedorHasProdutos = new HashSet(0);

    public TbFornecedor() {
    }

	
    public TbFornecedor(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public TbFornecedor(TbEntidade tbEntidade, Set tbEntradaEstoques, Set tbFornecedorHasProdutos) {
       this.tbEntidade = tbEntidade;
       this.tbEntradaEstoques = tbEntradaEstoques;
       this.tbFornecedorHasProdutos = tbFornecedorHasProdutos;
    }
   
    public Integer getForId() {
        return this.forId;
    }
    
    public void setForId(Integer forId) {
        this.forId = forId;
    }
    public TbEntidade getTbEntidade() {
        return this.tbEntidade;
    }
    
    public void setTbEntidade(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public Set getTbEntradaEstoques() {
        return this.tbEntradaEstoques;
    }
    
    public void setTbEntradaEstoques(Set tbEntradaEstoques) {
        this.tbEntradaEstoques = tbEntradaEstoques;
    }
    public Set getTbFornecedorHasProdutos() {
        return this.tbFornecedorHasProdutos;
    }
    
    public void setTbFornecedorHasProdutos(Set tbFornecedorHasProdutos) {
        this.tbFornecedorHasProdutos = tbFornecedorHasProdutos;
    }




}


