package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbFornecedorHasProduto generated by hbm2java
 */
public class TbFornecedorHasProduto  implements java.io.Serializable {


     private TbFornecedorHasProdutoId id;
     private TbFornecedor tbFornecedor;
     private TbProduto tbProduto;
     private float fhpValorCompra;

    public TbFornecedorHasProduto() {
    }

    public TbFornecedorHasProduto(TbFornecedorHasProdutoId id, TbFornecedor tbFornecedor, TbProduto tbProduto, float fhpValorCompra) {
       this.id = id;
       this.tbFornecedor = tbFornecedor;
       this.tbProduto = tbProduto;
       this.fhpValorCompra = fhpValorCompra;
    }
   
    public TbFornecedorHasProdutoId getId() {
        return this.id;
    }
    
    public void setId(TbFornecedorHasProdutoId id) {
        this.id = id;
    }
    public TbFornecedor getTbFornecedor() {
        return this.tbFornecedor;
    }
    
    public void setTbFornecedor(TbFornecedor tbFornecedor) {
        this.tbFornecedor = tbFornecedor;
    }
    public TbProduto getTbProduto() {
        return this.tbProduto;
    }
    
    public void setTbProduto(TbProduto tbProduto) {
        this.tbProduto = tbProduto;
    }
    public float getFhpValorCompra() {
        return this.fhpValorCompra;
    }
    
    public void setFhpValorCompra(float fhpValorCompra) {
        this.fhpValorCompra = fhpValorCompra;
    }




}


