package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbFuncionario generated by hbm2java
 */
public class TbFuncionario  implements java.io.Serializable {


     private int funcId;
     private TbUsuario tbUsuario;
     private TbStatus tbStatus;
     private TbFilial tbFilial;
     private TbCargo tbCargo;
     private TbEntidade tbEntidade;
     private TbAlmoxarifado tbAlmoxarifado;
     private Set tbFilials = new HashSet(0);
     private Set tbAlmoxarifados = new HashSet(0);

    public TbFuncionario() {
    }

	
    public TbFuncionario(int funcId, TbUsuario tbUsuario, TbStatus tbStatus, TbFilial tbFilial, TbCargo tbCargo, TbEntidade tbEntidade, TbAlmoxarifado tbAlmoxarifado) {
        this.funcId = funcId;
        this.tbUsuario = tbUsuario;
        this.tbStatus = tbStatus;
        this.tbFilial = tbFilial;
        this.tbCargo = tbCargo;
        this.tbEntidade = tbEntidade;
        this.tbAlmoxarifado = tbAlmoxarifado;
    }
    public TbFuncionario(int funcId, TbUsuario tbUsuario, TbStatus tbStatus, TbFilial tbFilial, TbCargo tbCargo, TbEntidade tbEntidade, TbAlmoxarifado tbAlmoxarifado, Set tbFilials, Set tbAlmoxarifados) {
       this.funcId = funcId;
       this.tbUsuario = tbUsuario;
       this.tbStatus = tbStatus;
       this.tbFilial = tbFilial;
       this.tbCargo = tbCargo;
       this.tbEntidade = tbEntidade;
       this.tbAlmoxarifado = tbAlmoxarifado;
       this.tbFilials = tbFilials;
       this.tbAlmoxarifados = tbAlmoxarifados;
    }
   
    public int getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(int funcId) {
        this.funcId = funcId;
    }
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    public TbStatus getTbStatus() {
        return this.tbStatus;
    }
    
    public void setTbStatus(TbStatus tbStatus) {
        this.tbStatus = tbStatus;
    }
    public TbFilial getTbFilial() {
        return this.tbFilial;
    }
    
    public void setTbFilial(TbFilial tbFilial) {
        this.tbFilial = tbFilial;
    }
    public TbCargo getTbCargo() {
        return this.tbCargo;
    }
    
    public void setTbCargo(TbCargo tbCargo) {
        this.tbCargo = tbCargo;
    }
    public TbEntidade getTbEntidade() {
        return this.tbEntidade;
    }
    
    public void setTbEntidade(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public TbAlmoxarifado getTbAlmoxarifado() {
        return this.tbAlmoxarifado;
    }
    
    public void setTbAlmoxarifado(TbAlmoxarifado tbAlmoxarifado) {
        this.tbAlmoxarifado = tbAlmoxarifado;
    }
    public Set getTbFilials() {
        return this.tbFilials;
    }
    
    public void setTbFilials(Set tbFilials) {
        this.tbFilials = tbFilials;
    }
    public Set getTbAlmoxarifados() {
        return this.tbAlmoxarifados;
    }
    
    public void setTbAlmoxarifados(Set tbAlmoxarifados) {
        this.tbAlmoxarifados = tbAlmoxarifados;
    }




}


