package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbGrupoPermissoes generated by hbm2java
 */
public class TbGrupoPermissoes  implements java.io.Serializable {


     private int gpermId;
     private String gpermNome;
     private String gpermDescricao;
     private String gpermPermisoes;
     private Set tbUsuarios = new HashSet(0);

    public TbGrupoPermissoes() {
    }

	
    public TbGrupoPermissoes(int gpermId, String gpermNome, String gpermDescricao, String gpermPermisoes) {
        this.gpermId = gpermId;
        this.gpermNome = gpermNome;
        this.gpermDescricao = gpermDescricao;
        this.gpermPermisoes = gpermPermisoes;
    }
    public TbGrupoPermissoes(int gpermId, String gpermNome, String gpermDescricao, String gpermPermisoes, Set tbUsuarios) {
       this.gpermId = gpermId;
       this.gpermNome = gpermNome;
       this.gpermDescricao = gpermDescricao;
       this.gpermPermisoes = gpermPermisoes;
       this.tbUsuarios = tbUsuarios;
    }
   
    public int getGpermId() {
        return this.gpermId;
    }
    
    public void setGpermId(int gpermId) {
        this.gpermId = gpermId;
    }
    public String getGpermNome() {
        return this.gpermNome;
    }
    
    public void setGpermNome(String gpermNome) {
        this.gpermNome = gpermNome;
    }
    public String getGpermDescricao() {
        return this.gpermDescricao;
    }
    
    public void setGpermDescricao(String gpermDescricao) {
        this.gpermDescricao = gpermDescricao;
    }
    public String getGpermPermisoes() {
        return this.gpermPermisoes;
    }
    
    public void setGpermPermisoes(String gpermPermisoes) {
        this.gpermPermisoes = gpermPermisoes;
    }
    public Set getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(Set tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }




}


