package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbOrdemServico generated by hbm2java
 */
public class TbOrdemServico  implements java.io.Serializable {


     private Integer osId;
     private TbVenda tbVenda;
     private TbServico tbServico;
     private float osValorServico;

    public TbOrdemServico() {
    }

    public TbOrdemServico(TbVenda tbVenda, TbServico tbServico, float osValorServico) {
       this.tbVenda = tbVenda;
       this.tbServico = tbServico;
       this.osValorServico = osValorServico;
    }
   
    public Integer getOsId() {
        return this.osId;
    }
    
    public void setOsId(Integer osId) {
        this.osId = osId;
    }
    public TbVenda getTbVenda() {
        return this.tbVenda;
    }
    
    public void setTbVenda(TbVenda tbVenda) {
        this.tbVenda = tbVenda;
    }
    public TbServico getTbServico() {
        return this.tbServico;
    }
    
    public void setTbServico(TbServico tbServico) {
        this.tbServico = tbServico;
    }
    public float getOsValorServico() {
        return this.osValorServico;
    }
    
    public void setOsValorServico(float osValorServico) {
        this.osValorServico = osValorServico;
    }




}


