package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbPedidoId generated by hbm2java
 */
public class TbPedidoId  implements java.io.Serializable {


     private int pedId;
     private String pedVenda;

    public TbPedidoId() {
    }

    public TbPedidoId(int pedId, String pedVenda) {
       this.pedId = pedId;
       this.pedVenda = pedVenda;
    }
   
    public int getPedId() {
        return this.pedId;
    }
    
    public void setPedId(int pedId) {
        this.pedId = pedId;
    }
    public String getPedVenda() {
        return this.pedVenda;
    }
    
    public void setPedVenda(String pedVenda) {
        this.pedVenda = pedVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbPedidoId) ) return false;
		 TbPedidoId castOther = ( TbPedidoId ) other; 
         
		 return (this.getPedId()==castOther.getPedId())
 && ( (this.getPedVenda()==castOther.getPedVenda()) || ( this.getPedVenda()!=null && castOther.getPedVenda()!=null && this.getPedVenda().equals(castOther.getPedVenda()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPedId();
         result = 37 * result + ( getPedVenda() == null ? 0 : this.getPedVenda().hashCode() );
         return result;
   }   


}


