package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbPedido generated by hbm2java
 */
public class TbPedido  implements java.io.Serializable {


     private TbPedidoId id;
     private TbEstoque tbEstoque;
     private TbVenda tbVenda;
     private float pedQuantidade;
     private float pedDesconto;

    public TbPedido() {
    }

    public TbPedido(TbPedidoId id, TbEstoque tbEstoque, TbVenda tbVenda, float pedQuantidade, float pedDesconto) {
       this.id = id;
       this.tbEstoque = tbEstoque;
       this.tbVenda = tbVenda;
       this.pedQuantidade = pedQuantidade;
       this.pedDesconto = pedDesconto;
    }
   
    public TbPedidoId getId() {
        return this.id;
    }
    
    public void setId(TbPedidoId id) {
        this.id = id;
    }
    public TbEstoque getTbEstoque() {
        return this.tbEstoque;
    }
    
    public void setTbEstoque(TbEstoque tbEstoque) {
        this.tbEstoque = tbEstoque;
    }
    public TbVenda getTbVenda() {
        return this.tbVenda;
    }
    
    public void setTbVenda(TbVenda tbVenda) {
        this.tbVenda = tbVenda;
    }
    public float getPedQuantidade() {
        return this.pedQuantidade;
    }
    
    public void setPedQuantidade(float pedQuantidade) {
        this.pedQuantidade = pedQuantidade;
    }
    public float getPedDesconto() {
        return this.pedDesconto;
    }
    
    public void setPedDesconto(float pedDesconto) {
        this.pedDesconto = pedDesconto;
    }




}


