package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0



/**
 * TbPedidoTransferencia generated by hbm2java
 */
public class TbPedidoTransferencia  implements java.io.Serializable {


     private int ptrId;
     private TbEstoque tbEstoque;
     private TbTransferenciasAlmoxarifado tbTransferenciasAlmoxarifado;
     private float ptrQuantidade;

    public TbPedidoTransferencia() {
    }

    public TbPedidoTransferencia(int ptrId, TbEstoque tbEstoque, TbTransferenciasAlmoxarifado tbTransferenciasAlmoxarifado, float ptrQuantidade) {
       this.ptrId = ptrId;
       this.tbEstoque = tbEstoque;
       this.tbTransferenciasAlmoxarifado = tbTransferenciasAlmoxarifado;
       this.ptrQuantidade = ptrQuantidade;
    }
   
    public int getPtrId() {
        return this.ptrId;
    }
    
    public void setPtrId(int ptrId) {
        this.ptrId = ptrId;
    }
    public TbEstoque getTbEstoque() {
        return this.tbEstoque;
    }
    
    public void setTbEstoque(TbEstoque tbEstoque) {
        this.tbEstoque = tbEstoque;
    }
    public TbTransferenciasAlmoxarifado getTbTransferenciasAlmoxarifado() {
        return this.tbTransferenciasAlmoxarifado;
    }
    
    public void setTbTransferenciasAlmoxarifado(TbTransferenciasAlmoxarifado tbTransferenciasAlmoxarifado) {
        this.tbTransferenciasAlmoxarifado = tbTransferenciasAlmoxarifado;
    }
    public float getPtrQuantidade() {
        return this.ptrQuantidade;
    }
    
    public void setPtrQuantidade(float ptrQuantidade) {
        this.ptrQuantidade = ptrQuantidade;
    }




}


