package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbProduto generated by hbm2java
 */
public class TbProduto  implements java.io.Serializable {


     private String pdtCodigo;
     private TbCategoriaProduto tbCategoriaProduto;
     private TbUnidadeMedida tbUnidadeMedida;
     private String pdtNome;
     private Set tbFornecedorHasProdutos = new HashSet(0);
     private Set tbEntradaEstoques = new HashSet(0);
     private Set tbEstoques = new HashSet(0);

    public TbProduto() {
    }

	
    public TbProduto(String pdtCodigo, TbCategoriaProduto tbCategoriaProduto, TbUnidadeMedida tbUnidadeMedida, String pdtNome) {
        this.pdtCodigo = pdtCodigo;
        this.tbCategoriaProduto = tbCategoriaProduto;
        this.tbUnidadeMedida = tbUnidadeMedida;
        this.pdtNome = pdtNome;
    }
    public TbProduto(String pdtCodigo, TbCategoriaProduto tbCategoriaProduto, TbUnidadeMedida tbUnidadeMedida, String pdtNome, Set tbFornecedorHasProdutos, Set tbEntradaEstoques, Set tbEstoques) {
       this.pdtCodigo = pdtCodigo;
       this.tbCategoriaProduto = tbCategoriaProduto;
       this.tbUnidadeMedida = tbUnidadeMedida;
       this.pdtNome = pdtNome;
       this.tbFornecedorHasProdutos = tbFornecedorHasProdutos;
       this.tbEntradaEstoques = tbEntradaEstoques;
       this.tbEstoques = tbEstoques;
    }
   
    public String getPdtCodigo() {
        return this.pdtCodigo;
    }
    
    public void setPdtCodigo(String pdtCodigo) {
        this.pdtCodigo = pdtCodigo;
    }
    public TbCategoriaProduto getTbCategoriaProduto() {
        return this.tbCategoriaProduto;
    }
    
    public void setTbCategoriaProduto(TbCategoriaProduto tbCategoriaProduto) {
        this.tbCategoriaProduto = tbCategoriaProduto;
    }
    public TbUnidadeMedida getTbUnidadeMedida() {
        return this.tbUnidadeMedida;
    }
    
    public void setTbUnidadeMedida(TbUnidadeMedida tbUnidadeMedida) {
        this.tbUnidadeMedida = tbUnidadeMedida;
    }
    public String getPdtNome() {
        return this.pdtNome;
    }
    
    public void setPdtNome(String pdtNome) {
        this.pdtNome = pdtNome;
    }
    public Set getTbFornecedorHasProdutos() {
        return this.tbFornecedorHasProdutos;
    }
    
    public void setTbFornecedorHasProdutos(Set tbFornecedorHasProdutos) {
        this.tbFornecedorHasProdutos = tbFornecedorHasProdutos;
    }
    public Set getTbEntradaEstoques() {
        return this.tbEntradaEstoques;
    }
    
    public void setTbEntradaEstoques(Set tbEntradaEstoques) {
        this.tbEntradaEstoques = tbEntradaEstoques;
    }
    public Set getTbEstoques() {
        return this.tbEstoques;
    }
    
    public void setTbEstoques(Set tbEstoques) {
        this.tbEstoques = tbEstoques;
    }




}


