package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbServico generated by hbm2java
 */
public class TbServico  implements java.io.Serializable {


     private Integer serId;
     private String serNome;
     private String serDescricao;
     private float serValorBase;
     private Set tbOrdemServicos = new HashSet(0);

    public TbServico() {
    }

	
    public TbServico(String serNome, String serDescricao, float serValorBase) {
        this.serNome = serNome;
        this.serDescricao = serDescricao;
        this.serValorBase = serValorBase;
    }
    public TbServico(String serNome, String serDescricao, float serValorBase, Set tbOrdemServicos) {
       this.serNome = serNome;
       this.serDescricao = serDescricao;
       this.serValorBase = serValorBase;
       this.tbOrdemServicos = tbOrdemServicos;
    }
   
    public Integer getSerId() {
        return this.serId;
    }
    
    public void setSerId(Integer serId) {
        this.serId = serId;
    }
    public String getSerNome() {
        return this.serNome;
    }
    
    public void setSerNome(String serNome) {
        this.serNome = serNome;
    }
    public String getSerDescricao() {
        return this.serDescricao;
    }
    
    public void setSerDescricao(String serDescricao) {
        this.serDescricao = serDescricao;
    }
    public float getSerValorBase() {
        return this.serValorBase;
    }
    
    public void setSerValorBase(float serValorBase) {
        this.serValorBase = serValorBase;
    }
    public Set getTbOrdemServicos() {
        return this.tbOrdemServicos;
    }
    
    public void setTbOrdemServicos(Set tbOrdemServicos) {
        this.tbOrdemServicos = tbOrdemServicos;
    }




}


