package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbSexo generated by hbm2java
 */
public class TbSexo  implements java.io.Serializable {


     private int sexId;
     private String sexDescricao;
     private Set tbEntidades = new HashSet(0);

    public TbSexo() {
    }

	
    public TbSexo(int sexId, String sexDescricao) {
        this.sexId = sexId;
        this.sexDescricao = sexDescricao;
    }
    public TbSexo(int sexId, String sexDescricao, Set tbEntidades) {
       this.sexId = sexId;
       this.sexDescricao = sexDescricao;
       this.tbEntidades = tbEntidades;
    }
   
    public int getSexId() {
        return this.sexId;
    }
    
    public void setSexId(int sexId) {
        this.sexId = sexId;
    }
    public String getSexDescricao() {
        return this.sexDescricao;
    }
    
    public void setSexDescricao(String sexDescricao) {
        this.sexDescricao = sexDescricao;
    }
    public Set getTbEntidades() {
        return this.tbEntidades;
    }
    
    public void setTbEntidades(Set tbEntidades) {
        this.tbEntidades = tbEntidades;
    }




}


