package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbStatus generated by hbm2java
 */
public class TbStatus  implements java.io.Serializable {


     private int staId;
     private String staDescricao;
     private Set tbFuncionarios = new HashSet(0);
     private Set tbUsuarios = new HashSet(0);

    public TbStatus() {
    }

	
    public TbStatus(int staId, String staDescricao) {
        this.staId = staId;
        this.staDescricao = staDescricao;
    }
    public TbStatus(int staId, String staDescricao, Set tbFuncionarios, Set tbUsuarios) {
       this.staId = staId;
       this.staDescricao = staDescricao;
       this.tbFuncionarios = tbFuncionarios;
       this.tbUsuarios = tbUsuarios;
    }
   
    public int getStaId() {
        return this.staId;
    }
    
    public void setStaId(int staId) {
        this.staId = staId;
    }
    public String getStaDescricao() {
        return this.staDescricao;
    }
    
    public void setStaDescricao(String staDescricao) {
        this.staDescricao = staDescricao;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(Set tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }




}


