package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoPagamento generated by hbm2java
 */
public class TbTipoPagamento  implements java.io.Serializable {


     private Integer tpId;
     private String tpDescricao;
     private Set tbVendas = new HashSet(0);

    public TbTipoPagamento() {
    }

	
    public TbTipoPagamento(String tpDescricao) {
        this.tpDescricao = tpDescricao;
    }
    public TbTipoPagamento(String tpDescricao, Set tbVendas) {
       this.tpDescricao = tpDescricao;
       this.tbVendas = tbVendas;
    }
   
    public Integer getTpId() {
        return this.tpId;
    }
    
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }
    public String getTpDescricao() {
        return this.tpDescricao;
    }
    
    public void setTpDescricao(String tpDescricao) {
        this.tpDescricao = tpDescricao;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }




}


