package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbTransferenciaStatus generated by hbm2java
 */
public class TbTransferenciaStatus  implements java.io.Serializable {


     private int trsId;
     private String trsNome;
     private String trsDescricao;
     private Set tbTransferenciasAlmoxarifados = new HashSet(0);
     private Set tbEntradas = new HashSet(0);

    public TbTransferenciaStatus() {
    }

	
    public TbTransferenciaStatus(int trsId, String trsNome) {
        this.trsId = trsId;
        this.trsNome = trsNome;
    }
    public TbTransferenciaStatus(int trsId, String trsNome, String trsDescricao, Set tbTransferenciasAlmoxarifados, Set tbEntradas) {
       this.trsId = trsId;
       this.trsNome = trsNome;
       this.trsDescricao = trsDescricao;
       this.tbTransferenciasAlmoxarifados = tbTransferenciasAlmoxarifados;
       this.tbEntradas = tbEntradas;
    }
   
    public int getTrsId() {
        return this.trsId;
    }
    
    public void setTrsId(int trsId) {
        this.trsId = trsId;
    }
    public String getTrsNome() {
        return this.trsNome;
    }
    
    public void setTrsNome(String trsNome) {
        this.trsNome = trsNome;
    }
    public String getTrsDescricao() {
        return this.trsDescricao;
    }
    
    public void setTrsDescricao(String trsDescricao) {
        this.trsDescricao = trsDescricao;
    }
    public Set getTbTransferenciasAlmoxarifados() {
        return this.tbTransferenciasAlmoxarifados;
    }
    
    public void setTbTransferenciasAlmoxarifados(Set tbTransferenciasAlmoxarifados) {
        this.tbTransferenciasAlmoxarifados = tbTransferenciasAlmoxarifados;
    }
    public Set getTbEntradas() {
        return this.tbEntradas;
    }
    
    public void setTbEntradas(Set tbEntradas) {
        this.tbEntradas = tbEntradas;
    }




}


