package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbTransferenciasAlmoxarifado generated by hbm2java
 */
public class TbTransferenciasAlmoxarifado  implements java.io.Serializable {


     private int traId;
     private TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoDestino;
     private TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoOrigem;
     private TbTransferenciaStatus tbTransferenciaStatus;
     private Set tbPedidoTransferencias = new HashSet(0);

    public TbTransferenciasAlmoxarifado() {
    }

	
    public TbTransferenciasAlmoxarifado(int traId, TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoDestino, TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoOrigem, TbTransferenciaStatus tbTransferenciaStatus) {
        this.traId = traId;
        this.tbAlmoxarifadoByTraAlmoxarifadoDestino = tbAlmoxarifadoByTraAlmoxarifadoDestino;
        this.tbAlmoxarifadoByTraAlmoxarifadoOrigem = tbAlmoxarifadoByTraAlmoxarifadoOrigem;
        this.tbTransferenciaStatus = tbTransferenciaStatus;
    }
    public TbTransferenciasAlmoxarifado(int traId, TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoDestino, TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoOrigem, TbTransferenciaStatus tbTransferenciaStatus, Set tbPedidoTransferencias) {
       this.traId = traId;
       this.tbAlmoxarifadoByTraAlmoxarifadoDestino = tbAlmoxarifadoByTraAlmoxarifadoDestino;
       this.tbAlmoxarifadoByTraAlmoxarifadoOrigem = tbAlmoxarifadoByTraAlmoxarifadoOrigem;
       this.tbTransferenciaStatus = tbTransferenciaStatus;
       this.tbPedidoTransferencias = tbPedidoTransferencias;
    }
   
    public int getTraId() {
        return this.traId;
    }
    
    public void setTraId(int traId) {
        this.traId = traId;
    }
    public TbAlmoxarifado getTbAlmoxarifadoByTraAlmoxarifadoDestino() {
        return this.tbAlmoxarifadoByTraAlmoxarifadoDestino;
    }
    
    public void setTbAlmoxarifadoByTraAlmoxarifadoDestino(TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoDestino) {
        this.tbAlmoxarifadoByTraAlmoxarifadoDestino = tbAlmoxarifadoByTraAlmoxarifadoDestino;
    }
    public TbAlmoxarifado getTbAlmoxarifadoByTraAlmoxarifadoOrigem() {
        return this.tbAlmoxarifadoByTraAlmoxarifadoOrigem;
    }
    
    public void setTbAlmoxarifadoByTraAlmoxarifadoOrigem(TbAlmoxarifado tbAlmoxarifadoByTraAlmoxarifadoOrigem) {
        this.tbAlmoxarifadoByTraAlmoxarifadoOrigem = tbAlmoxarifadoByTraAlmoxarifadoOrigem;
    }
    public TbTransferenciaStatus getTbTransferenciaStatus() {
        return this.tbTransferenciaStatus;
    }
    
    public void setTbTransferenciaStatus(TbTransferenciaStatus tbTransferenciaStatus) {
        this.tbTransferenciaStatus = tbTransferenciaStatus;
    }
    public Set getTbPedidoTransferencias() {
        return this.tbPedidoTransferencias;
    }
    
    public void setTbPedidoTransferencias(Set tbPedidoTransferencias) {
        this.tbPedidoTransferencias = tbPedidoTransferencias;
    }




}


