package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbUnidadeMedida generated by hbm2java
 */
public class TbUnidadeMedida  implements java.io.Serializable {


     private String umSigla;
     private String umDescricao;
     private String umTipo;
     private Set tbProdutos = new HashSet(0);

    public TbUnidadeMedida() {
    }

	
    public TbUnidadeMedida(String umSigla, String umDescricao, String umTipo) {
        this.umSigla = umSigla;
        this.umDescricao = umDescricao;
        this.umTipo = umTipo;
    }
    public TbUnidadeMedida(String umSigla, String umDescricao, String umTipo, Set tbProdutos) {
       this.umSigla = umSigla;
       this.umDescricao = umDescricao;
       this.umTipo = umTipo;
       this.tbProdutos = tbProdutos;
    }
   
    public String getUmSigla() {
        return this.umSigla;
    }
    
    public void setUmSigla(String umSigla) {
        this.umSigla = umSigla;
    }
    public String getUmDescricao() {
        return this.umDescricao;
    }
    
    public void setUmDescricao(String umDescricao) {
        this.umDescricao = umDescricao;
    }
    public String getUmTipo() {
        return this.umTipo;
    }
    
    public void setUmTipo(String umTipo) {
        this.umTipo = umTipo;
    }
    public Set getTbProdutos() {
        return this.tbProdutos;
    }
    
    public void setTbProdutos(Set tbProdutos) {
        this.tbProdutos = tbProdutos;
    }




}


