package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUsuario generated by hbm2java
 */
public class TbUsuario  implements java.io.Serializable {


     private String usuUsuario;
     private TbStatus tbStatus;
     private TbGrupoPermissoes tbGrupoPermissoes;
     private String usuSenha;
     private Date usuValidade;
     private Set tbFuncionarios = new HashSet(0);

    public TbUsuario() {
    }

	
    public TbUsuario(String usuUsuario, TbStatus tbStatus, TbGrupoPermissoes tbGrupoPermissoes, String usuSenha) {
        this.usuUsuario = usuUsuario;
        this.tbStatus = tbStatus;
        this.tbGrupoPermissoes = tbGrupoPermissoes;
        this.usuSenha = usuSenha;
    }
    public TbUsuario(String usuUsuario, TbStatus tbStatus, TbGrupoPermissoes tbGrupoPermissoes, String usuSenha, Date usuValidade, Set tbFuncionarios) {
       this.usuUsuario = usuUsuario;
       this.tbStatus = tbStatus;
       this.tbGrupoPermissoes = tbGrupoPermissoes;
       this.usuSenha = usuSenha;
       this.usuValidade = usuValidade;
       this.tbFuncionarios = tbFuncionarios;
    }
   
    public String getUsuUsuario() {
        return this.usuUsuario;
    }
    
    public void setUsuUsuario(String usuUsuario) {
        this.usuUsuario = usuUsuario;
    }
    public TbStatus getTbStatus() {
        return this.tbStatus;
    }
    
    public void setTbStatus(TbStatus tbStatus) {
        this.tbStatus = tbStatus;
    }
    public TbGrupoPermissoes getTbGrupoPermissoes() {
        return this.tbGrupoPermissoes;
    }
    
    public void setTbGrupoPermissoes(TbGrupoPermissoes tbGrupoPermissoes) {
        this.tbGrupoPermissoes = tbGrupoPermissoes;
    }
    public String getUsuSenha() {
        return this.usuSenha;
    }
    
    public void setUsuSenha(String usuSenha) {
        this.usuSenha = usuSenha;
    }
    public Date getUsuValidade() {
        return this.usuValidade;
    }
    
    public void setUsuValidade(Date usuValidade) {
        this.usuValidade = usuValidade;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }




}


