package codemarket.model.pojo;
// Generated 20/09/2023 14:26:58 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbVenda generated by hbm2java
 */
public class TbVenda  implements java.io.Serializable {


     private Integer venId;
     private TbTipoPagamento tbTipoPagamento;
     private TbCliente tbCliente;
     private Date venData;
     private Set tbPedidos = new HashSet(0);
     private Set tbOrdemServicos = new HashSet(0);

    public TbVenda() {
    }

	
    public TbVenda(TbTipoPagamento tbTipoPagamento, Date venData) {
        this.tbTipoPagamento = tbTipoPagamento;
        this.venData = venData;
    }
    public TbVenda(TbTipoPagamento tbTipoPagamento, TbCliente tbCliente, Date venData, Set tbPedidos, Set tbOrdemServicos) {
       this.tbTipoPagamento = tbTipoPagamento;
       this.tbCliente = tbCliente;
       this.venData = venData;
       this.tbPedidos = tbPedidos;
       this.tbOrdemServicos = tbOrdemServicos;
    }
   
    public Integer getVenId() {
        return this.venId;
    }
    
    public void setVenId(Integer venId) {
        this.venId = venId;
    }
    public TbTipoPagamento getTbTipoPagamento() {
        return this.tbTipoPagamento;
    }
    
    public void setTbTipoPagamento(TbTipoPagamento tbTipoPagamento) {
        this.tbTipoPagamento = tbTipoPagamento;
    }
    public TbCliente getTbCliente() {
        return this.tbCliente;
    }
    
    public void setTbCliente(TbCliente tbCliente) {
        this.tbCliente = tbCliente;
    }
    public Date getVenData() {
        return this.venData;
    }
    
    public void setVenData(Date venData) {
        this.venData = venData;
    }
    public Set getTbPedidos() {
        return this.tbPedidos;
    }
    
    public void setTbPedidos(Set tbPedidos) {
        this.tbPedidos = tbPedidos;
    }
    public Set getTbOrdemServicos() {
        return this.tbOrdemServicos;
    }
    
    public void setTbOrdemServicos(Set tbOrdemServicos) {
        this.tbOrdemServicos = tbOrdemServicos;
    }




}


